---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    debian_packages:
      - mc
    debian_hostname: ""
    debian_search_domain: ""
    debian_dns_servers: []
    debian_timezone: Etc/UTC

  roles:
    - denis-volin.debian
